language: node_js
node_js:
  - 12

sudo: required
services:
 - docker

jobs:
  include:
    - stage: test
      script:
        - npm install
        - npm test
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - make build tag
      - make publish
      - rm -f /home/travis/.docker/config.json