language: generic

sudo: required
services:
 - docker

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - make build tag
      - make publish
      - rm -f /home/travis/.docker/config.json