---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anz-test-2-deployment
  labels:
    app: anz-test-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anz-test-2
  template:
    metadata:
      labels:
        app: anz-test-2
    spec:
      containers:
          - name: anz-test-2
            image: sammcj/anz-test-2
            ports:
              - containerPort: 8000
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1024Mi"
                cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: anz-test-2-service
spec:
  selector:
    app: anz-test-2
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer